"use strict";

/*
 * Last Shelter missile references.
 *
 * MISSILE is the active v1.250.102 contract observed from a freshly
 * registered account on the current reference server. The older eight-row
 * init payload is retained only as LEGACY_MISSILE_INIT_OBSERVED so historical
 * data remains available without overriding the current server behavior.
 *
 * Mutable fields (totalNum, unReceive, lastLaunchTime, unlockFlag, unlock,
 * plugin) are generated by missileFreshRuntimeHazirla instead of being mixed
 * into static cost/timer configuration.
 */

function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

const MISSILE = deepFreeze({
  "53301": {
    money:1000000,
    electricity:2500000,
    food:1000000,
    time:3600,
    item_need:"212007;800"
  },
  "53302": {
    money:1000000,
    electricity:2500000,
    wood:1000000,
    time:7200,
    item_need:"212007;1600"
  },
  "53303": {
    money:1000000,
    electricity:3750000,
    wood:1500000,
    time:10800,
    item_need:"212007;2400"
  },
  "53304": {
    money:2000000,
    electricity:7500000,
    water:3000000,
    time:10800,
    item_need:"212007;4000"
  },
  "53305": {
    money:4000000,
    electricity:7500000,
    water:3000000,
    launch_cd:14400,
    time:21600,
    item_need:"212007;8000"
  },
  "53306": {
    money:100000,
    electricity:250000,
    water:100000,
    time:720,
    item_need:"212007;80"
  }
});

const LEGACY_MISSILE_INIT_OBSERVED = deepFreeze({
  "53301": { wood:200000, iron:20000, def_value:1000, speed:1, item_need:"200047;15", unlock_level:1, atk_value:0, time:10800, capacity:1, status:500901 },
  "53302": { wood:1500000, def_value:2000, speed:2, item_need:"200047;200", unlock_level:2, atk_value:3, time:28800, capacity:1, missile_effect:53500 },
  "53303": { wood:500000, iron:500000, def_value:4500, speed:5, item_need:"200047;500", unlock_level:4, atk_value:5, time:54000, capacity:2 },
  "53304": { iron:50000, def_value:4500, speed:4, item_need:"200047;1000", unlock_level:5, atk_value:4, time:86400, capacity:2, missile_effect:53501 },
  "53305": { wood:500000, iron:100000, def_value:2000, speed:2, item_need:"200047;525", unlock_level:3, atk_value:10, time:28800, capacity:1 },
  "53306": { iron:200000, def_value:6000, speed:4.5, item_need:"200047;1200", unlock_level:6, atk_value:5, time:86400, capacity:2, missile_effect:53502 },
  "53307": { wood:1500000, iron:500000, status:500905, def_value:5000, speed:1.5, item_need:"200047;1500", unlock_level:7, atk_value:10, time:144000, capacity:2, missile_effect:53503 },
  "53308": { wood:500000, def_value:5000, speed:1.5, item_need:"200047;200", unlock_level:8, atk_value:1, time:86400, capacity:1 }
});

function clone(value) {
  return value == null ? value : JSON.parse(JSON.stringify(value));
}

function missileAl(id) {
  const key = String(id == null ? "" : id).trim();
  const row = MISSILE[key];
  return row ? clone(row) : null;
}

function missileIds() {
  return Object.keys(MISSILE);
}

function missileFreshRuntimeHazirla() {
  return missileIds().map(missileId => ({
    unlockFlag:0,
    missileId,
    unlock:true,
    plugin:"",
    ...missileAl(missileId),
    totalNum:0,
    unReceive:0,
    lastLaunchTime:0
  }));
}

function legacyMissileInitObservedAl(id) {
  const key = String(id == null ? "" : id).trim();
  const row = LEGACY_MISSILE_INIT_OBSERVED[key];
  return row ? clone(row) : null;
}

module.exports = {
  MISSILE,
  LEGACY_MISSILE_INIT_OBSERVED,
  missileAl,
  missileIds,
  missileFreshRuntimeHazirla,
  legacyMissileInitObservedAl
};
