"use strict";
const assert=require("assert");
const {lastShelterAuxiliaryCommandleriniQeydEt}=require("./runtime_last_shelter_auxiliary_reference_commands");
class R{constructor(){this.routes=new Map()}register(t,h,o){this.routes.set(t,{h,o});return this}}
(async()=>{
 const state={lastShelterResourceRuntime:{regTime:1000}};
 const r=new R(); lastShelterAuxiliaryCommandleriniQeydEt(r,{getOrCreatePlayerState:()=>state});
 for(const n of ["troop.reference.list","troop.reference.get","resource.info","item.tuning.list","item.tuning.get","starter_account.info","goods.structure.list","goods.structure.get","store.reward.get","store.reward.catalog","alliance.group_purchase.info","alliance.group_purchase.offer.get","fort.troop.list","fort.troop.get","troop_transfer.reference.list","troop_transfer.reference.get","shop.reference.list","vip_store.info","repay.info","activity.reference.list","activity.reference.get","missile.info","seven_days.info","truck.info","world.info","battlefield.get"]) assert.deepStrictEqual(r.routes.get(n).o,{authRequired:true,mutation:false});
 const sent=[],ws={_authedPlayerId:"p1"},send=(_,x)=>sent.push(x);
 await r.routes.get("troop.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4978}); assert.strictEqual(Object.keys(sent[0].troops107x).length,33); assert.strictEqual(Object.keys(sent[0].troops1073x).length,10);
 await r.routes.get("troop.reference.get").h({ws,msg:{playerId:"p1",id:"107309"},send,nowMs:()=>4979}); assert.strictEqual(sent[1].troop.speedVerifiedStatic,false); assert(sent[1].observedSpeeds.length>=3);
 state.resources={food:12,wood:34,chip:5};
 await r.routes.get("resource.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4980}); assert.strictEqual(sent[2].resources.food,12); assert.strictEqual(sent[2].resources.db_timezone_offset,4); assert.strictEqual(sent[2].fields.length,15);
 await r.routes.get("item.tuning.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4981}); assert.strictEqual(sent[3].tuning.cd_time.k10,2592000);
 await r.routes.get("item.tuning.get").h({ws,msg:{playerId:"p1",id:"world_marchtime"},send,nowMs:()=>4982}); assert.strictEqual(sent[4].tuning.k1,0.82);
 await r.routes.get("starter_account.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4983}); assert.strictEqual(sent[5].itemTemplates.length,2); assert.strictEqual(sent[5].queueLayout.length,12); assert.strictEqual(sent[5].queues.length,12);
 await r.routes.get("goods.structure.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4984}); assert.strictEqual(sent[6].goods.length,36);
 await r.routes.get("goods.structure.get").h({ws,msg:{playerId:"p1",itemId:"200016"},send,nowMs:()=>4985}); assert.strictEqual(sent[7].good.sales.length,4); assert.strictEqual(sent[7].good.sales[3].count,1000);
 await r.routes.get("store.reward.catalog").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4986}); assert.strictEqual(sent[8].count,401);
 await r.routes.get("store.reward.get").h({ws,msg:{playerId:"p1",storeId:"200500"},send,nowMs:()=>4987}); assert.strictEqual(sent[9].reward[0].value.id,"200331");
 await r.routes.get("alliance.group_purchase.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4988}); assert.strictEqual(sent[10].reference.offers.length,6); assert.strictEqual(sent[10].runtime.progress,0);
 await r.routes.get("alliance.group_purchase.offer.get").h({ws,msg:{playerId:"p1",goodsId:"207055"},send,nowMs:()=>4989}); assert.strictEqual(sent[11].offer.key,"k3");
 await r.routes.get("fort.troop.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4990}); assert.strictEqual(sent[12].troops.length,20); assert.strictEqual(sent[12].troops.find(x=>x.id==="107900").free,1);
 await r.routes.get("fort.troop.get").h({ws,msg:{playerId:"p1",id:"107900"},send,nowMs:()=>4991}); assert.strictEqual(sent[13].troop.trainingTimeSeconds,40);
 await r.routes.get("troop_transfer.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4992}); assert.strictEqual(sent[14].trees.length,4); assert.strictEqual(sent[14].trees[0].details.length,12);
 await r.routes.get("troop_transfer.reference.get").h({ws,msg:{playerId:"p1",transferType:1,pointType:"12"},send,nowMs:()=>4993}); assert.strictEqual(sent[15].point.id,"109048");
 await r.routes.get("shop.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4994}); assert.strictEqual(sent[16].shops.length,8); assert.strictEqual(sent[16].shops[0].itemTuplesRaw.length,8);
 await r.routes.get("vip_store.info").h({ws,msg:{playerId:"p1",refreshTime:123},send,nowMs:()=>4995}); assert.strictEqual(sent[17].panel.vipstore.level,1); assert.strictEqual(sent[17].panel.vipstore.refreshTime,123);
 state.lastShelterAuxiliaryRuntime={repayinfo:{payPoint:2000,claimedPoints:[400]}};
 await r.routes.get("repay.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4996}); assert.strictEqual(sent[18].eligibleRewards.length,2); assert.strictEqual(sent[18].claimableRewards.length,1); assert.strictEqual(sent[18].claimableRewards[0].point,2000);
 await r.routes.get("activity.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4997}); assert.strictEqual(sent[19].activities.length,12);
 await r.routes.get("activity.reference.get").h({ws,msg:{playerId:"p1",id:"57041"},send,nowMs:()=>4998}); assert.strictEqual(sent[2]0.activity.reward[0].value.id,"207081");
 await r.routes.get("missile.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4999}); assert(sent[2]1.missiles.length>0); const original=state.lastShelterMissileRuntime.missiles[0].totalNum; sent[2]1.missiles[0].totalNum=999; assert.strictEqual(state.lastShelterMissileRuntime.missiles[0].totalNum,original);
 await r.routes.get("seven_days.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5000}); assert.strictEqual(sent[2]2.activity.startTime,1000); assert.strictEqual(sent[2]2.topology.valid,true);
 await r.routes.get("truck.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5001}); assert.strictEqual(sent[2]3.trucks[0].xmlId,"20001001");
 await r.routes.get("world.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5002}); assert.strictEqual(sent[2]4.world.stamina,100); assert.strictEqual(sent[2]4.battlefieldMaps.length,3); sent[2]4.world.stamina=1; assert.strictEqual(state.lastShelterWorldRuntime.stamina,100);
 await r.routes.get("battlefield.get").h({ws,msg:{playerId:"p1",id:"220100"},send,nowMs:()=>5003}); assert.strictEqual(sent[2]5.map.id,"220100"); assert(sent[2]5.restrictions.bannedMissileIds.includes("53303"));
 await r.routes.get("battlefield.get").h({ws,msg:{playerId:"p1",id:"missing"},send,nowMs:()=>5004}); assert.strictEqual(sent[2]6.code,"BATTLEFIELD_NOT_FOUND");
 console.log("PASS: auxiliary verified runtime reads");
})().catch(e=>{console.error(e);process.exit(1)});
