"use strict";
const assert=require("assert");
const {lastShelterAuxiliaryCommandleriniQeydEt}=require("./runtime_last_shelter_auxiliary_reference_commands");
class R{constructor(){this.routes=new Map()}register(t,h,o){assert(!this.routes.has(t), "duplicate route: "+t);this.routes.set(t,{h,o});return this}}
(async()=>{
 const state={lastShelterResourceRuntime:{regTime:1000}};
 const r=new R(); lastShelterAuxiliaryCommandleriniQeydEt(r,{getOrCreatePlayerState:()=>state});
 for(const n of ["fresh_init.envelope.info","starter_city.info","troop.reference.list","troop.reference.get","resource.info","item.tuning.list","item.tuning.get","starter_account.info","goods.structure.list","goods.structure.get","store.reward.get","store.reward.catalog","alliance.group_purchase.offer.get","fort.troop.list","fort.troop.get","troop_transfer.state","troop_transfer.reference.list","troop_transfer.reference.get","shop.reference.list","vip_store.info","activity.reference.list","activity.reference.get","missile.info","seven_days.info","truck.info","world.info","battlefield.get"]) assert.deepStrictEqual(r.routes.get(n).o,{authRequired:true,mutation:false});
 const sent=[],ws={_authedPlayerId:"p1"},send=(_,x)=>sent.push(x);
 await r.routes.get("fresh_init.envelope.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4976}); assert.strictEqual(sent.at(-1).runtime.vip.nextDayScore,20); assert.strictEqual(sent.at(-1).runtime.vipstoreLevel,1); sent.at(-1).runtime.vip.level=99; assert.strictEqual(state.lastShelterFreshInitEnvelopeRuntime.vip.level,0);
 await r.routes.get("starter_city.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4977}); assert.strictEqual(sent.at(-1).buildings.length,2); assert.strictEqual(sent.at(-1).buildListConfig.length,10); assert(sent.at(-1).reference.unlock.current.malformed.includes("600003;0600004;0"));
 await r.routes.get("troop.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4978}); assert.strictEqual(Object.keys(sent.at(-1).troops107x).length,33); assert.strictEqual(Object.keys(sent.at(-1).troops1073x).length,10);
 await r.routes.get("troop.reference.get").h({ws,msg:{playerId:"p1",id:"107309"},send,nowMs:()=>4979}); assert.strictEqual(sent.at(-1).troop.speedVerifiedStatic,false); assert(sent.at(-1).observedSpeeds.length>=3);
 state.resources={food:12,wood:34,chip:5};
 await r.routes.get("resource.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4980}); assert.strictEqual(sent.at(-1).resources.food,12); assert.strictEqual(sent.at(-1).resources.db_timezone_offset,4); assert.strictEqual(sent.at(-1).fields.length,15);
 await r.routes.get("item.tuning.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4981}); assert.strictEqual(sent.at(-1).tuning.cd_time.k10,2592000);
 await r.routes.get("item.tuning.get").h({ws,msg:{playerId:"p1",id:"world_marchtime"},send,nowMs:()=>4982}); assert.strictEqual(sent.at(-1).tuning.k1,0.82);
 await r.routes.get("starter_account.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4983}); assert.strictEqual(sent.at(-1).itemTemplates.length,2); assert.strictEqual(sent.at(-1).queueLayout.length,12); assert.strictEqual(sent.at(-1).queues.length,12);
 await r.routes.get("goods.structure.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4984}); assert.strictEqual(sent.at(-1).goods.length,35);
 await r.routes.get("goods.structure.get").h({ws,msg:{playerId:"p1",itemId:"200016"},send,nowMs:()=>4985}); assert.strictEqual(sent.at(-1).good.sales.length,4); assert.strictEqual(sent.at(-1).good.sales[3].count,1000);
 await r.routes.get("store.reward.catalog").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4986}); assert.strictEqual(sent.at(-1).count,401);
 await r.routes.get("store.reward.get").h({ws,msg:{playerId:"p1",storeId:"200500"},send,nowMs:()=>4987}); assert.strictEqual(sent.at(-1).reward[0].value.id,"200331");
 await r.routes.get("alliance.group_purchase.offer.get").h({ws,msg:{playerId:"p1",goodsId:"207055"},send,nowMs:()=>4989}); assert.strictEqual(sent.at(-1).offer.key,"k3");
 await r.routes.get("fort.troop.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4990}); assert.strictEqual(sent.at(-1).troops.length,20); assert.strictEqual(sent.at(-1).troops.find(x=>x.id==="107900").free,1);
 await r.routes.get("fort.troop.get").h({ws,msg:{playerId:"p1",id:"107900"},send,nowMs:()=>4991}); assert.strictEqual(sent.at(-1).troop.trainingTimeSeconds,40);
 state.lastShelterTroopTransferRuntime=[{type:1,total:10,level:6,todayTranTimes:3,power:0,exp:777,singleCostAmount:10,details:[{id:"109034",pointType:"5",level:0}]}];
 await r.routes.get("troop_transfer.state").h({ws,msg:{playerId:"p1"},send,nowMs:()=>49915}); assert.strictEqual(sent.at(-1).trees[0].total,50); assert.strictEqual(sent.at(-1).trees[0].power,244); assert.strictEqual(sent.at(-1).trees[0].exp,777); assert.deepStrictEqual(sent.at(-1).trees[0].details[0].effects,{"1561":-5,"1531":-5,"1541":-5,"1551":-5});
 await r.routes.get("troop_transfer.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4992}); assert.strictEqual(sent.at(-1).trees.length,4); assert.strictEqual(sent.at(-1).trees[0].details.length,12);
 await r.routes.get("troop_transfer.reference.get").h({ws,msg:{playerId:"p1",transferType:1,pointType:"12"},send,nowMs:()=>4993}); assert.strictEqual(sent.at(-1).point.id,"109048");
 await r.routes.get("shop.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4994}); assert.strictEqual(sent.at(-1).shops.length,48); assert.strictEqual(sent.at(-1).shops[0].itemTuplesRaw.length,8);
 await r.routes.get("vip_store.info").h({ws,msg:{playerId:"p1",refreshTime:123},send,nowMs:()=>4995}); assert.strictEqual(sent.at(-1).panel.vipstore.level,1); assert.strictEqual(sent.at(-1).panel.vipstore.refreshTime,0);
 await r.routes.get("activity.reference.list").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4997}); assert.strictEqual(sent.at(-1).activities.length,12);
 await r.routes.get("activity.reference.get").h({ws,msg:{playerId:"p1",id:"57041"},send,nowMs:()=>4998}); assert.strictEqual(sent.at(-1).activity.reward[0].value.id,"207081");
 await r.routes.get("missile.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>4999}); assert(sent.at(-1).missiles.length>0); const original=state.lastShelterMissileRuntime.missiles[0].totalNum; sent.at(-1).missiles[0].totalNum=999; assert.strictEqual(state.lastShelterMissileRuntime.missiles[0].totalNum,original);
 await r.routes.get("seven_days.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5000}); assert.strictEqual(sent.at(-1).activity.startTime,1000); assert.strictEqual(sent.at(-1).topology.valid,true);
 await r.routes.get("truck.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5001}); assert.strictEqual(sent.at(-1).trucks[0].xmlId,"20001001");
 await r.routes.get("world.info").h({ws,msg:{playerId:"p1"},send,nowMs:()=>5002}); assert.strictEqual(sent.at(-1).world.stamina,100); assert.strictEqual(sent.at(-1).battlefieldMaps.length,3); sent.at(-1).world.stamina=1; assert.strictEqual(state.lastShelterWorldRuntime.stamina,100);
 await r.routes.get("battlefield.get").h({ws,msg:{playerId:"p1",id:"220100"},send,nowMs:()=>5003}); assert.strictEqual(sent.at(-1).map.id,"220100"); assert(sent.at(-1).restrictions.bannedMissileIds.includes("53303"));
 await r.routes.get("battlefield.get").h({ws,msg:{playerId:"p1",id:"missing"},send,nowMs:()=>5004}); assert.strictEqual(sent.at(-1).code,"BATTLEFIELD_NOT_FOUND");
 console.log("PASS: auxiliary verified runtime reads");
})().catch(e=>{console.error(e);process.exit(1)});
