BEGIN;

-- ============================================================
-- MİQRASİYA CƏDVƏLİ
-- ============================================================

CREATE TABLE IF NOT EXISTS miqrasiyalar (
    ad TEXT PRIMARY KEY,
    tetbiq_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- HESABLAR
-- ============================================================

CREATE TABLE IF NOT EXISTS hesablar (
    hesab_id TEXT PRIMARY KEY,
    oyuncu_id TEXT NOT NULL UNIQUE,

    esas_email TEXT NOT NULL,
    ikinci_email TEXT,

    email_tesdiqlenib BOOLEAN NOT NULL DEFAULT FALSE,

    sifre_hash TEXT NOT NULL,
    pin_hash TEXT,

    status TEXT NOT NULL DEFAULT 'aktiv'
        CHECK (
            status IN (
                'aktiv',
                'bloklanib',
                'silinme_gozleyir',
                'silinib'
            )
        ),

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    yenilenme_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    silinme_vaxti TIMESTAMPTZ
);


CREATE UNIQUE INDEX IF NOT EXISTS idx_hesablar_esas_email_lower
ON hesablar (
    LOWER(esas_email)
);


CREATE UNIQUE INDEX IF NOT EXISTS idx_hesablar_ikinci_email_lower
ON hesablar (
    LOWER(ikinci_email)
)
WHERE ikinci_email IS NOT NULL;


-- ============================================================
-- EMAIL TƏSDİQİ
-- ============================================================

CREATE TABLE IF NOT EXISTS email_tesdiqleri (
    hesab_id TEXT PRIMARY KEY
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,

    kod_hash TEXT NOT NULL,
    duz TEXT NOT NULL,

    bitme_vaxti TIMESTAMPTZ NOT NULL,

    cehd_sayi INTEGER NOT NULL DEFAULT 0
        CHECK (cehd_sayi >= 0),

    son_gonderilme_vaxti TIMESTAMPTZ NOT NULL,

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- ŞİFRƏ SIFIRLAMA
-- ============================================================

CREATE TABLE IF NOT EXISTS sifre_sifirlama_sorqulari (
    sorqu_id TEXT PRIMARY KEY,

    hesab_id TEXT NOT NULL
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,

    kod_hash TEXT NOT NULL,
    duz TEXT NOT NULL,

    bitme_vaxti TIMESTAMPTZ NOT NULL,

    cehd_sayi INTEGER NOT NULL DEFAULT 0,

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    istifade_vaxti TIMESTAMPTZ
);


CREATE INDEX IF NOT EXISTS idx_sifre_sifirlama_hesab
ON sifre_sifirlama_sorqulari(hesab_id);


-- ============================================================
-- HESAB SESSİYALARI
-- ============================================================

CREATE TABLE IF NOT EXISTS hesab_sessiyalari (
    sessiya_id TEXT PRIMARY KEY,

    hesab_id TEXT NOT NULL
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,

    refresh_token_hash TEXT NOT NULL UNIQUE,

    cihaz_id TEXT,

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    son_istifade_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    bitme_vaxti TIMESTAMPTZ NOT NULL,
    legv_vaxti TIMESTAMPTZ
);


CREATE INDEX IF NOT EXISTS idx_hesab_sessiyalari_hesab
ON hesab_sessiyalari(hesab_id);


-- ============================================================
-- GOOGLE / APPLE / FACEBOOK / GAME CENTER
-- ============================================================

CREATE TABLE IF NOT EXISTS hesab_provayderleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hesab_id TEXT NOT NULL
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,

    provayder TEXT NOT NULL,
    provayder_istifadeci_id TEXT NOT NULL,

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (
        provayder,
        provayder_istifadeci_id
    ),

    UNIQUE (
        hesab_id,
        provayder
    )
);


-- ============================================================
-- İTİRİLMİŞ HESAB BƏRPASI
-- ============================================================

CREATE TABLE IF NOT EXISTS hesab_berpa_sorqulari (
    sorqu_id TEXT PRIMARY KEY,

    email TEXT,
    oyuncu_id TEXT,
    komandir_adi TEXT,
    elave_melumat TEXT,

    status TEXT NOT NULL DEFAULT 'gozleyir'
        CHECK (
            status IN (
                'gozleyir',
                'yoxlanilir',
                'qebul_edildi',
                'redd_edildi',
                'baglandi'
            )
        ),

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    yenilenme_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- AUDİT JURNALI
-- ============================================================

CREATE TABLE IF NOT EXISTS hesab_audit_jurnali (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hesab_id TEXT
        REFERENCES hesablar(hesab_id)
        ON DELETE SET NULL,

    oyuncu_id TEXT,

    hadise_novu TEXT NOT NULL,

    detallar JSONB NOT NULL DEFAULT '{}'::jsonb,

    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_hesab_audit_hesab
ON hesab_audit_jurnali(hesab_id);


CREATE INDEX IF NOT EXISTS idx_hesab_audit_oyuncu
ON hesab_audit_jurnali(oyuncu_id);


-- ============================================================
-- APP ROLE İCAZƏLƏRİ
-- ============================================================

GRANT CONNECT
ON DATABASE demiryumruq
TO demiryumruq_app;


GRANT USAGE
ON SCHEMA public
TO demiryumruq_app;


GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
ON ALL TABLES IN SCHEMA public
TO demiryumruq_app;


GRANT
    USAGE,
    SELECT
ON ALL SEQUENCES IN SCHEMA public
TO demiryumruq_app;


ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
ON TABLES
TO demiryumruq_app;


ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT
    USAGE,
    SELECT
ON SEQUENCES
TO demiryumruq_app;


COMMIT;