-- ============================================================
-- HESAB ETIBARLI CIHAZ + MEC BURI PIN KILIDI
-- ============================================================

CREATE TABLE IF NOT EXISTS hesab_etibarli_cihazlar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hesab_id TEXT NOT NULL
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,
    cihaz_hash TEXT NOT NULL,
    ilk_tesdiq_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    son_istifade_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    legv_vaxti TIMESTAMPTZ,
    UNIQUE (hesab_id, cihaz_hash)
);

CREATE INDEX IF NOT EXISTS idx_hesab_etibarli_cihaz_aktiv
    ON hesab_etibarli_cihazlar (hesab_id, cihaz_hash)
    WHERE legv_vaxti IS NULL;

CREATE TABLE IF NOT EXISTS hesab_cihaz_pin_sorqulari (
    sorqu_id TEXT PRIMARY KEY,
    hesab_id TEXT NOT NULL
        REFERENCES hesablar(hesab_id)
        ON DELETE CASCADE,
    cihaz_hash TEXT NOT NULL,
    meqsed TEXT NOT NULL
        CHECK (meqsed IN ('login', 'refresh', 'recovery')),
    bitme_vaxti TIMESTAMPTZ NOT NULL,
    yaradilma_vaxti TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    istifade_vaxti TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_hesab_cihaz_pin_aktiv
    ON hesab_cihaz_pin_sorqulari (hesab_id, cihaz_hash, yaradilma_vaxti DESC)
    WHERE istifade_vaxti IS NULL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON hesab_etibarli_cihazlar, hesab_cihaz_pin_sorqulari
TO demiryumruq_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO demiryumruq_app;
